app/controllers/SiteController.php
<?php

namespace app\controllers;

use app\components\ChartHelper;
use app\components\OdnoklassnikiSDK;
use app\components\SocialUser;
use app\models\ContactForm;
use app\models\DateFilterForm;
use app\models\Feature;
use app\models\User;
use app\models\WatchedUser;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\swiftmailer\Mailer;
use yii\web\HttpException;

class SiteController extends BaseController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
        if ($action->id == 'login' && array_key_exists('token', $_POST)) {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }

    public function actionIndex()
    {
        $dateFilterForm = new DateFilterForm();
        $dateFilterForm->period = DateFilterForm::PERIOD_REALTIME;
        $dateFilterForm->load(Yii::$app->request->get());
        if (!$dateFilterForm->validate()) {
            Yii::$app->session->setFlash('dateFilterFormError', $dateFilterForm->getErrorsText());
            $dateFilterForm->period = DateFilterForm::PERIOD_REALTIME;
        };

        $addUserModel = new WatchedUser();

        return $this->render('index', [
            'dateFilterForm' => $dateFilterForm,
            'addUserModel' => $addUserModel,
        ]);
    }

    public function actionLogin()
    {
        $this->layout = 'empty';

        if (!\Yii::$app->user->isGuest) {
            return $this->redirect(Yii::$app->user->returnUrl);
        }

        if (isset($_POST['token'])) {
            $s = file_get_contents('http://ulogin.ru/token.php?token=' . $_POST['token'] . '&host=' . $_SERVER['HTTP_HOST']);
            $data = json_decode($s, true);
            $identity = $data['identity'];
            $user = User::findByIdentity($identity);
            if (!$user) {
                $user = new User();
                $user->attributes = $data;
                if (!$user->save()) {
                    throw new HttpException(500, 'Не удалось создать пользователя');
                }
            }

            if (!Yii::$app->user->login($user, 3600 * 24 * 365)) {
                throw new HttpException(500, 'Не удалось авторизоваться');
            }
            return $this->goHome();
        }

        return $this->render('login');
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionFeatures()
    {
        $features = Feature::find()->where('deleted_at is null')->all();

        return $this->render('features', ['models' => $features]);
    }

    public function actionLikeFeature()
    {
        if (!isset($_POST['id'])) {
            Yii::$app->end();
        }

        return Feature::findOne($_POST['id'])->like($_POST['like']);
    }

    public function actionContacts()
    {
        $mailForm = new ContactForm();
        if (Yii::$app->request->post('ContactForm')) {
            $mailForm->load(Yii::$app->request->post());
            if ($mailForm->validate()) {
                $success = Yii::$app->mailer->compose()
                    ->setTo(['alexgivi@nextmail.ru', 'allush@yandex.ru'])
                    ->setFrom([$mailForm->email => $mailForm->name])
                    ->setSubject($mailForm->subject)
                    ->setTextBody($mailForm->body)
                    ->send();

                if ($success) {
                    Yii::$app->session->setFlash('mailSendOk');
                } else {
                    Yii::$app->session->setFlash('mailSendError');
                }
            }
        }
        return $this->render('contacts', ['mailForm' => $mailForm]);
    }

    /**
     * Получить данные для построения графика
     * главной страницы
     *
     * @param int $period
     * @param $startDate
     * @param $endDate
     * @return string
     */
    public function actionGetChartData($period = DateFilterForm::PERIOD_REALTIME, $startDate = null, $endDate = null)
    {
        $dateFilterForm = new DateFilterForm();
        $dateFilterForm->period = $period;
        $dateFilterForm->from = $startDate;
        $dateFilterForm->to = $endDate;

        $helper = new ChartHelper();
        return $this->renderPartial('_users', [
            'data' => $helper->getChartData($dateFilterForm->getStartDate(), $dateFilterForm->getEndDate())
        ]);
    }

    public function actionGetUserData($link)
    {
        return SocialUser::fromLink($link)->getInfo();
    }

}

app/controllers/WatchedUserController.php
<?php

namespace app\controllers;

use app\models\WatchedUser;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

class WatchedUserController extends BaseController
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $query = WatchedUser::find()->where([
            'user_id' => Yii::$app->user->id,
        ]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreate()
    {
        $model = new WatchedUser();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if (Yii::$app->request->isPost) {
            $model->load(Yii::$app->request->post());
            if ($model->save()) {
                $redirect = Yii::$app->request->post('redirect');
                return $this->redirect($redirect ?: ['index']);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if (Yii::$app->request->isPost) {
            $model->load(Yii::$app->request->post());
            if ($model->save()) {
                return $this->redirect(['index']);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * @param $id
     * @return WatchedUser
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        $model = WatchedUser::findOne($id);
        if ($model === null) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

        return $model;
    }
}

app/views/layouts/empty.php
<?php
/**
 * @var $this \yii\web\View
 * @var $content string
 */
?>

<?php
use yii\helpers\Html;
use app\assets\AppAsset;
use app\assets\FontAwesomeAsset;

AppAsset::register($this);
FontAwesomeAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<?= $content ?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

app/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\assets\FontAwesomeAsset;

AppAsset::register($this);
FontAwesomeAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'SW',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Главная', 'url' => ['/site/index']],
            ['label' => 'Отслеживаемые', 'url' => ['/watched-user/index']],
            ['label' => 'Возможности', 'url' => ['/site/about']],
            ['label' => 'Рекомендации', 'url' => ['/site/features']],
            ['label' => 'Контакты', 'url' => ['/site/contacts']],
            Yii::$app->user->isGuest ?
                ['label' => 'Вход', 'url' => ['/site/login']] :
                [
                    'label' => 'Выход (' . Yii::$app->user->identity->name . ')',
                    'url' => ['/site/logout'],
                    'linkOptions' => ['data-method' => 'post'],
                ],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; SW <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>